### ISSUE TITLE
Iteration 2 Checklist

### ISSUE THREAD

**Issue by jobbotrock** [bjjdestroyer/intention-timer#24]
1. Activity button borders: 
- [x] **Rubric:** Activity button icons and border change color on "click" event.
- [x] **Rubric:** Fix button border issue
- [x] **Rubric:** Colors border timer "behind" the scenes once 
2. **Activity Description** input field
- [ ] **Responsiveness** limit character for text input **OR**  text wrap for multiple lines
- [x] **Rubric:** Require input field for Activity button functionality
3. Minute and Second input fields
- [x] **Rubric** Only accepts numbers
- [x] **Rubric** The **`e`** should not appear when entered
4. **Capture Phase** for **Start Activity** button functionality 
- [x] **Rubric** Checks if minute and second inputs are entered 
- [x] **Rubric:** Checks for values in description field
- [x] **Rubric:** If no input is received, throw error message "A description is required." when user clicks button without inputs
- [x] **Rubric** Minutes and seconds inputs remain the same after error message
5. **Bubbling Phase:** Instantiate Activity Class
- [ ] **Rubric** Instantiates are old friend Activity class
- [x] **Rubric** Initiates timer clock view
- [ ] **Rubric** Circle border color matches corresponding Activity buttons 
- [x] **Rubric** Minutes and seconds match timer clock display
