### ISSUE TITLE
**Iteration 2 Refactor Milestone**

### ISSUE THREAD

**Issue by jobbotrock** [bjjdestroyer/intention-timer#25]
1. Iteration 2 Lessons 
- [ ] We all bring different and unique strengths - our goal is to leverage them moving forward
- [ ] Life is really tough right now: **We can't always bring our best and that's OKAY!**
- [ ] Working remote is challenging: **We're building resilience and adapting to our challenges

2. Iteration 2 Refactor
**HTML**
- [ ] Accommodates people with visual impairments **4**
- [ ] Easy to read markups and follow proper naming conventions **3**
- [ ] Uses semantic HTML whenever possible, clean sturcture **2**

**CSS** 
- [ ] Uses BEM and SMACCS naming conventions for Classes **4**
- [ ] Uses DRY principles  -removes repetitive rules and code block **3**
- [ ] Uses organizational conventions for the entire stylesheet, less than 5 media queries **2**

**Javascript**
- [ ] Dev empathy, no **global variables**, functions less than 10 lines, use logical operators **4**
- [ ] Event delegation, DRY/SRP code, no DOM logic, arguments & params, uses localStorage **3**
- [ ] No extra code, if/else to handle multiple paths of logic error, no data model separation **2**
